[WIP] v7: Allow single array range in highlightRanges prop - Code Pane
FormidableLabs/spectacle pull request #959
Opened 2020-11-13 21:52 UTC by chrisipanaque

### Description

After verifying that issue #918 was fixed in `main-7`, it was recommended by @carlos-kelly to also allow the user to pass a single array range `[3, 5]` to the `highlightRange` prop in Code Pane

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### How Has This Been Tested?

To reproduce, pass the following values to the `highlightRanges` prop:

• `highlightRanges = [6, 8]`
![v7-single-array](https://user-images.githubusercontent.com/16032631/99123135-73148e00-25b4-11eb-9db8-405fe1ace195.gif)

• `highlightRanges = [[1], [3], [6, 8]]`
![v7-2d-array](https://user-images.githubusercontent.com/16032631/99123438-0948b400-25b5-11eb-85a0-74c8dff93570.gif)

• `highlightRanges={[1, 3, 5, [6, 8]]}`
![v7-2d-array-with-numbers](https://user-images.githubusercontent.com/16032631/99124154-7c065f00-25b6-11eb-9205-7b4e9b3faf35.gif)

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My code follows the style guidelines of this project (I have run `yarn format`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (I have run `yarn test`)
- [x] My changes generate no new warnings

2020-11-17 18:22 UTC, carlos-kelly approved these changes

2020-11-17 18:22 UTC, carlos-kelly commented on src/components/code-pane.js
> +      highlightRanges.every(element => typeof element === 'number');
Nice use of `every`

2020-11-17 18:25 UTC, carlos-kelly requested changes
I found one use case where if we pass `[null, null]` we get a crash on line 133 on extracting the first element.

2020-11-18 00:34 UTC, chrisipanaque commented
> I found one use case where if we pass `[null, null]` we get a crash on line 133 on extracting the first element. I think in `getRangeFormat` we should also sanitize for null or undefined as elements in the array.

Code updated. Thanks! Please let me know if any additional changes.

**A question about another edge case found:**

If a user passes in the following array format:
```js
highlightRanges={[
  1, 
  3, 
  [null, 8]
]}
```

Should the sub array `[null, 8]` be treated as a single digit range `[8]` or convert the beginning digit to 0 `[0, 8]`

2020-12-04 22:36 UTC, chrisipanaque commented
@carlos-kelly Also, should this PR also include updates to the documentation or should that be completed in a different PR?

2020-12-06 17:16 UTC, carlos-kelly commented
@chrisipanaque That's up to you. We will do a documentation audit before we launch 7.0 and we know the biggest changed API is `CodePane`.

2020-12-06 17:32 UTC, carlos-kelly approved these changes
This is also good to go!

2020-12-07 15:20 UTC, upatel32 approved these changes

2020-12-07 17:02 UTC, chrisipanaque commented
> **A question about another edge case found:**
> 
> If a user passes in the following array format:
> 
> ```js
> highlightRanges={[
>   1, 
>   3, 
>   [null, 8]
> ]}
> ```
> 
> Should the sub array `[null, 8]` be treated as a single digit range `[8]` or convert the beginning digit to 0 `[0, 8]`?

This issue is now resolved with the use of newly added propTypes, and logging a "Failed prop type" warning in case a user sends any null values to `highlightRanges`.

I will create a new PR to update documentation.

Thanks all! 🎉

2020-12-07 17:09 UTC, merged