Merge v7 Spectacle into main
FormidableLabs/spectacle pull request #980
Opened 2021-02-02 15:29 UTC by carlos-kelly

Every commit inside v7 has been PR'd individually into the `main-7` branch but this will set the `main` branch to the v7 codebase.

2021-02-02 20:03 UTC, ryan-roemer requested changes
Some mostly minor things:

- [x] `docs` aren't passing CI. `cd docs && yarn && yarn check-ci` fails presumably because of upgraded eslint config in root that we use in `docs/`
- [ ] `yarn && yarn build-one-page` produce git changes in root.
- [ ] Animated bullets aren't working in spectacle/examples/one-page.html?immediate=true&slide=3&slideElement=1

2021-02-02 23:34 UTC, upatel32 approved these changes
Everything looks good! I left a few comments that were all mainly about syntactic sugar. Feel free to ignore them!

2021-02-02 23:34 UTC, upatel32 commented on src/utils/remark-rehype-presenter-notes.js
> +    if (node.children[0].type !== 'text') return;
nit: not important, worth combining these two into one statement?

2021-02-02 23:34 UTC, upatel32 commented on src/hooks/use-slides.js
> +    }
nit: could do

```
const nextSlideIds = slides.map(slide => slide.dataset.slideId);
```

2021-02-02 23:34 UTC, upatel32 commented on src/hooks/use-aspect-ratio-fitting.js
> +    if (!containerRef.current) return;
same as before, could combine these

2021-02-02 23:34 UTC, upatel32 commented on src/hooks/use-aspect-ratio-fitting.js
> +      }
I was thinking if we wanted to use const we could use a ternary operator here, but I think the way it currently is helps readability

2021-02-02 23:34 UTC, upatel32 commented on src/components/code-pane.js
> +  }
this could be ternary

2021-02-03 18:17 UTC, ryan-roemer approved these changes
Works great! 🎉

2021-02-04 13:32 UTC, merged